trim:
    ##Trimming parameters for trimmomatic v 0.36
    adapters_file: "/home1/datawork/lmilhade/pmarg/TruSeq2-PE.fa"
    leading: "LEADING:26"
    trailing: "TRAILING:26"
    slidingwindow: "SLIDINGWINDOW:20:20"
    minlen: "MINLEN:40"
    illuminaclip: "2:30:10"
    ncpus: 8

